# Generated by Django 5.2.4 on 2025-07-22 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gc_requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garbagerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=12),
        ),
    ]
